### ISSUE TITLE
Hi, great work, but how can I use it as the backbone of my object detection network? thanks for answer

### ISSUE THREAD

**Issue by w-x-j00** [mmaaz60/EdgeNeXt#3]

**Comment by mmaaz60** [comment]
Hi @w-x-j00,

You can use our [EdgeNeXt model](https://github.com/mmaaz60/EdgeNeXt/blob/30bb4847017e45cae998148857c96f87d69f079e/models/model.py#L52) and modify it such that it returns feature maps instead of classification scores. You can do by modifying [forward](https://github.com/mmaaz60/EdgeNeXt/blob/30bb4847017e45cae998148857c96f87d69f079e/models/edgenext.py#L85) and [forward_features](https://github.com/mmaaz60/EdgeNeXt/blob/30bb4847017e45cae998148857c96f87d69f079e/models/edgenext.py#L73) functions.

I hope that would be helpful, let me know if you will have any questions. Good Luck!
