### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by 35454652** [mmaaz60/EdgeNeXt#7]
Traceback (most recent call last):
  File "D:/python/pycharm/EdgeNeXt-main/main.py", line 501, in <module>
    main(args)
  File "D:/python/pycharm/EdgeNeXt-main/main.py", line 370, in main
    print("Max WD = %.7f, Min WD = %.7f" % (max(wd_schedule_values), min(wd_schedule_values)))
ValueError: max() arg is an empty sequence

Hello, this is a problem I'm having while trying to run your code, do you know why? Thank you!

**Comment by mmaaz60** [comment]
Hi @35454652,

Thank Yon for creating this issue. Could you please share the exact command you are running?


Thanks

**Comment by 35454652** [comment]
Of course, I run main.py with the command arguments given by readme.md.

**Comment by mmaaz60** [comment]
> Of course, I run main.py with the command arguments given by readme.md.

Hi @35454652,

I double checked following the instructions in README for evaluation of `edgenext_small` model. Specifically, running the following commands work for me,

`wget https://github.com/mmaaz60/EdgeNeXt/releases/download/v1.0/edgenext_small.pth`

`python main.py --model edgenext_small --eval True --batch_size 16 --data_path /share/data/drive_1/imagenet_1k --output_dir output --resume edgenext_small.pth`

Where `/share/data/drive_1/imagenet_1k` is the path to the ImageNet-1K dataset on my machine. Please explain if you are doing anything different. Also, it would be helpful if you can share the details about your environment. Thank you

**Comment by mmaaz60** [comment]
Please feel free to reopen if you are still facing the issue, would be happy to help.

**Comment by alvarohghg** [comment]
Hello, I'm facing the same problem. I'm not using the imagenet due to storage constraints but I was trying to test it with 4 images (image1.jpeg, image2.jpeg, etc) located with a structure like the one indicated in the README (located inside the class folders, inside train and val, inside the input folder) . I'm also using the command you mentioned: python main.py --model edgenext_small --eval True --batch_size 16 --data_path input --output_dir output --resume edgenext_small.pth
